name=input("please enter your name : ")
age =input ("please enter your age : ")
location= input ("please enter where you live : ")
a= int(age)
b= str(location)
c=str(name)
print(" hello your name is "+ c)
print("you are " + str(a))
print("you live "+ b)